### Before building the project, make sure you have specified the required environment variables in the .env file
version: "3.9"
networks:
  ahs_local:
    driver: bridge
services:
  ### Databases ###
  db-ahs:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ahs_local
    restart: always
  ### Eureka ###
  app-eureka-server:
    image: awesomehardwaresupply_app_eureka_server
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: awesomehardwaresupply_app_eureka_server
    ports:
      - "8761:8761"
    networks:
      - ahs_local
  ### Authentication ###
  app-authentication:
    image: awesomehardwaresupply_app_authentication
    build:
      context: .
      dockerfile: authentication/Dockerfile
    container_name: awesomehardwaresupply_app_authentication
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-ahs:5432/ahs_authentication
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - security.b-crypt-encoder-strength=${B_CRYPT_ENCODER_STRENGTH}
      - security.jwt.secret=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=prod
      - spring.application.name=AUTHENTICATION
      - eureka.client.serviceUrl.defaultZone=http://app-eureka-server:8761/eureka/
    networks:
      - ahs_local
    depends_on:
      - db-ahs
      - app-eureka-server
  ### Knowledgebase ###
  app-knowledgebase:
    image: awesomehardwaresupply_app_knowledgebase
    build:
      context: .
      dockerfile: knowledgebase/Dockerfile
    container_name: awesomehardwaresupply_app_knowledgebase
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-ahs:5432/ahs_knowledgebase
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - spring.application.name=KNOWLEDGEBASE
      - eureka.client.serviceUrl.defaultZone=http://app-eureka-server:8761/eureka/
    networks:
      - ahs_local
    depends_on:
      - db-ahs
      - app-eureka-server
  ### Price Schedule ###
  app-price-schedule:
    image: awesomehardwaresupply_app_price_schedule
    build:
      context: .
      dockerfile: priceschedule/Dockerfile
    container_name: awesomehardwaresupply_app_price_schedule
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-ahs:5432/ahs_price_schedule
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - spring.application.name=PRICE_SCHEDULE
      - eureka.client.serviceUrl.defaultZone=http://app-eureka-server:8761/eureka/
    networks:
      - ahs_local
    depends_on:
      - db-ahs
      - app-eureka-server
  ### Gateway ###
  app-gateway:
    image: awesomehardwaresupply_app_gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: awesomehardwaresupply_app_gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - security.jwt.secret=${JWT_SECRET}
      - AUTHENTICATION_SERVICE_URI=lb://AUTHENTICATION
      - KNOWLEDGEBASE_SERVICE_URI=lb://KNOWLEDGEBASE
      - PRICE_SCHEDULE_SERVICE_URI=lb://PRICE_SCHEDULE
      - eureka.client.serviceUrl.defaultZone=http://app-eureka-server:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - ahs_local
    depends_on:
      - app-authentication
      - app-knowledgebase
      - app-price-schedule
      - app-eureka-server