version: "3.9"
services:
  ### Eureka Server ###
  app_eureka_server:
    image: ndiac/awesomehardwaresupply_app_eureka_server
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: awesomehardwaresupply_app_eureka_server
  ### Gateway ###
  app_gateway:
    image: ndiac/awesomehardwaresupply_app_gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: awesomehardwaresupply_app_gateway
  ### Authentication ###
  app_authentication:
    image: ndiac/awesomehardwaresupply_app_authentication
    build:
      context: .
      dockerfile: authentication/Dockerfile
    container_name: awesomehardwaresupply_app_authentication
  ### Knowledgebase ###
  app_knowledgebase:
    image: ndiac/awesomehardwaresupply_app_knowledgebase
    build:
      context: .
      dockerfile: knowledgebase/Dockerfile
    container_name: awesomehardwaresupply_app_knowledgebase