version: "3.9"
services:
  ### Eureka Server ###
  app_eureka_server:
    image: ndiac/awesomehardwaresupply_app_eureka_server
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: awesomehardwaresupply_app_eureka_server