version: "3.9"
services:
  ### Gateway ###
  app_gateway:
    image: ndiac/awesomehardwaresupply_app_gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: awesomehardwaresupply_app_gateway
  ### Authentication ###
  app_authentication:
    image: ndiac/awesomehardwaresupply_app_authentication
    build:
      context: .
      dockerfile: authentication/Dockerfile
    container_name: awesomehardwaresupply_app_authentication
    environment:
      - SPRING_LIQUIBASE_CHANGE-LOG=classpath:db/liquibase-changelog.xml
      - SPRING_PROFILES_ACTIVE=prod
  ### Knowledgebase ###
  app_knowledgebase:
    image: ndiac/awesomehardwaresupply_app_knowledgebase
    build:
      context: .
      dockerfile: knowledgebase/Dockerfile
    container_name: awesomehardwaresupply_app_knowledgebase
    environment:
      - SPRING_LIQUIBASE_CHANGE-LOG=classpath:db/liquibase-changelog.xml
  ### Price Schedule ###
  app_price_schedule:
    image: ndiac/awesomehardwaresupply_app_price_schedule
    build:
      context: .
      dockerfile: priceschedule/Dockerfile
    container_name: awesomehardwaresupply_app_price_schedule
    environment:
      - SPRING_LIQUIBASE_CHANGE-LOG=classpath:db/liquibase-changelog.xml