apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: ndiac/awesomehardwaresupply_app_authentication
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: authentication-db-configmap
                  key: database_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: authentication-db-secret
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-db-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: gateway-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080