apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ndiac/awesomehardwaresupply_app_gateway
          ports:
            - containerPort: 8080
          env:
            - name: AUTHENTICATION_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: authentication_service_uri
            - name: KNOWLEDGEBASE_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: knowledgebase_service_uri
            - name: PRICE_SCHEDULE_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: gateway-configmap
                  key: price_schedule_service_uri
            - name: SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: security-jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32100